using UnityEngine;

[DefaultExecutionOrder(-100)] // DO NOT NOT NOT USE IN GAME COMPANIES!!!! Ensures that this script runs before other scripts that might depend on the input actions being initialized. 
public class InputManager : MonoBehaviour
{
   public static ApplicationActions Actions { get; private set; } //referring to C# class generated by Unity's Input System, which contains the input actions defined in the Input Actions asset.

    private void Awake()
    {
        Actions = new ApplicationActions();
        Actions.Enable();
    }
}
